/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    MapPinInfo: typeof import('./src/components/sub_components/MapPinInfo.vue')['default']
    MobileNavigator: typeof import('./src/components/mobile/MobileNavigator.vue')['default']
    MyInfo: typeof import('./src/components/pc/sub_components/infopage_sub_components/MyInfo.vue')['default']
    MyMessage: typeof import('./src/components/pc/sub_components/infopage_sub_components/MyMessage.vue')['default']
    MyMessage_Mobile: typeof import('./src/components/mobile/sub_components/infopage_sub_components/MyMessage_Mobile.vue')['default']
    MyPin: typeof import('./src/components/pc/sub_components/infopage_sub_components/MyPin.vue')['default']
    MyPost: typeof import('./src/components/pc/sub_components/infopage_sub_components/MyPost.vue')['default']
    MyPost_Mobile: typeof import('./src/components/mobile/sub_components/infopage_sub_components/MyPost_Mobile.vue')['default']
    NewPost: typeof import('./src/components/sub_components/NewPost.vue')['default']
    PCInforPage: typeof import('./src/components/pc/PCInforPage.vue')['default']
    PCLoginView: typeof import('./src/components/pc/PCLoginView.vue')['default']
    PCMapHomepage: typeof import('./src/components/pc/PCMapHomepage.vue')['default']
    PCPageHeader: typeof import('./src/components/pc/PCPageHeader.vue')['default']
    PCPostPage: typeof import('./src/components/pc/PCPostPage.vue')['default']
    PCRegisterView: typeof import('./src/components/pc/PCRegisterView.vue')['default']
    PlaceSearch: typeof import('./src/components/sub_components/mappage_sub_components/PlaceSearch.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwitchPos: typeof import('./src/components/sub_components/mappage_sub_components/SwitchPos.vue')['default']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
  }
}
