name: Deploy to Remote Server

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - feature/CICD

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        npm install
    - name: Build project
      run: |
        npm run build

    - name: Connect to Remote
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_KEY }}
        script: |
          cd Deploy
          rm -rf Agile_Frontend
          git clone git@github.com:Enqurance/Agile_Frontend.git
          cd Agile_Frontend
          git checkout dev